"""Compatibility exports for storage helper functions."""

from __future__ import annotations

from typing import Any

from .storage_capacity import (
    _aggregate_available,
    _aggregate_capacity,
    _aggregate_usage,
    _pool_available,
    _pool_capacity,
    _pool_usage,
)
from .storage_common import (
    BYTES_PER_GIB,
    DEGRADED_STATUSES,
    DISK_PROBLEM_HINTS,
    HEALTHY_STATUSES,
    POOL_MAINTENANCE_HINTS,
    UUID_LIKE_RE,
    _bytes_to_gib,
    _first_number,
    _looks_like_machine_identifier,
    _normalize_percent,
    _percentage,
    _slug,
    _sum_known,
    _text,
)
from .storage_drives import (
    DRIVE_INDEX_KEY_RE,
    DRIVE_ID_KEYS,
    DRIVE_METRIC_KEYS,
    DRIVE_POOL_KEYS,
    DRIVE_STRONG_ID_KEYS,
    _collect_drive_like_dicts,
    _cache_drives,
    _drive_attributes,
    _drive_bad_sectors,
    _drive_capacity,
    _drive_health,
    _drive_is_at_risk,
    _drive_key,
    _drive_life_span,
    _drive_media_type,
    _drive_model,
    _drive_name,
    _drive_power_on_hours,
    _drive_temperature,
    _drive_uncorrectable_sectors,
    _is_drive_like_dict,
    _legacy_drive_index,
    _pool_at_risk_drive_count,
    _pool_average_drive_temperature,
    _pool_drive_count,
    _pool_drive_temperatures,
    _pool_drives,
    _raw_drive_health,
)
from .storage_pools import (
    POOL_INDEX_KEY_RE,
    RAID_LEVEL_KEYS,
    _aggregate_status,
    _at_risk_disk_count,
    _average_disk_temperature,
    _cache_status,
    _degraded_pool_count,
    _find_progress_in_tree,
    _maintenance_pool_count,
    _pool_from_key,
    _pool_has_problem,
    _pool_in_maintenance,
    _pool_key,
    _pool_name,
    _pool_progress,
    _pool_raid_level,
    _pool_rebuild_progress,
    _pool_status,
    _pool_sync_progress,
    _pools,
    _raw_pool_status,
    _ssd_wear,
)
from .storage_system import (
    _cpu_percent,
    _cpu_temperature,
    _memory_percent,
    _system_ip,
    _system_status,
    _system_uptime_hours,
    _system_uptime_readable,
)
from .storage_throughput import (
    _parse_throughput_value,
    _read_throughput_mb_s,
    _throughput_from_disks_mb_s,
    _throughput_key_hints,
    _throughput_mb_s,
    _write_throughput_mb_s,
)
from .system_metadata import (
    drive_version as _drive_version,
    normalized_token as _normalized_token,
    system_payload as _system_payload,
    unifi_os_version as _unifi_os_version,
)

__all__ = [
    "BYTES_PER_GIB",
    "DEGRADED_STATUSES",
    "DISK_PROBLEM_HINTS",
    "HEALTHY_STATUSES",
    "POOL_MAINTENANCE_HINTS",
    "UUID_LIKE_RE",
    "_aggregate_available",
    "_aggregate_capacity",
    "_aggregate_usage",
    "_pool_available",
    "_pool_capacity",
    "_pool_usage",
    "_bytes_to_gib",
    "_first_number",
    "_looks_like_machine_identifier",
    "_normalize_percent",
    "_percentage",
    "_slug",
    "_sum_known",
    "_text",
    "DRIVE_INDEX_KEY_RE",
    "DRIVE_ID_KEYS",
    "DRIVE_METRIC_KEYS",
    "DRIVE_POOL_KEYS",
    "DRIVE_STRONG_ID_KEYS",
    "_collect_drive_like_dicts",
    "_cache_drives",
    "_drive_attributes",
    "_drive_bad_sectors",
    "_drive_capacity",
    "_drive_health",
    "_drive_is_at_risk",
    "_drive_key",
    "_drive_life_span",
    "_drive_media_type",
    "_drive_model",
    "_drive_name",
    "_drive_power_on_hours",
    "_drive_temperature",
    "_drive_uncorrectable_sectors",
    "_is_drive_like_dict",
    "_legacy_drive_index",
    "_pool_at_risk_drive_count",
    "_pool_average_drive_temperature",
    "_pool_drive_count",
    "_pool_drive_temperatures",
    "_pool_drives",
    "_raw_drive_health",
    "POOL_INDEX_KEY_RE",
    "RAID_LEVEL_KEYS",
    "_aggregate_status",
    "_at_risk_disk_count",
    "_average_disk_temperature",
    "_cache_status",
    "_degraded_pool_count",
    "_find_progress_in_tree",
    "_maintenance_pool_count",
    "_pool_from_key",
    "_pool_has_problem",
    "_pool_in_maintenance",
    "_pool_key",
    "_pool_name",
    "_pool_progress",
    "_pool_raid_level",
    "_pool_rebuild_progress",
    "_pool_status",
    "_pool_sync_progress",
    "_pools",
    "_raw_pool_status",
    "_ssd_wear",
    "_cpu_percent",
    "_cpu_temperature",
    "_memory_percent",
    "_system_ip",
    "_system_status",
    "_system_uptime_hours",
    "_system_uptime_readable",
    "_parse_throughput_value",
    "_read_throughput_mb_s",
    "_throughput_from_disks_mb_s",
    "_throughput_key_hints",
    "_throughput_mb_s",
    "_write_throughput_mb_s",
    "_drive_version",
    "_normalized_token",
    "_system_payload",
    "_unifi_os_version",
]
